### ISSUE TITLE
Error with asp.net Core 2.2 app

### ISSUE THREAD

**Issue by JoeYong** [serilog-contrib/Serilog.Sinks.MicrosoftTeams.Alternative#1]
After installing via NuGet, upon running the application (without setting any additional configuration), I received this error -

HTTP Error 502.5 - ANCM Out-Of-Process Startup Failure
Common causes of this issue:
The application process failed to start
The application process started but then stopped
The application process started but failed to listen on the configured port
Troubleshooting steps:
Check the system event log for error messages
Enable logging the application process' stdout messages
Attach a debugger to the application process and inspect
For more information visit: https://go.microsoft.com/fwlink/?LinkID=808681

I am on .Net Core 2.2. I suspect this is a compatibility issue.

**Comment by JoeYong** [comment]
So is this repo being maintained at all or dead? Should remove it from Serilog provided Sinks link if it is dead.

**Comment by livehealthy** [comment]
Need Microsoft Help on asp.net Core 2.2! We should have high expectation to Microsoft, right? 👎

**Comment by cssriraman** [comment]
> After installing via NuGet, upon running the application (without setting any additional configuration), I received this error -
> 
> HTTP Error 502.5 - ANCM Out-Of-Process Startup Failure
> Common causes of this issue:
> The application process failed to start
> The application process started but then stopped
> The application process started but failed to listen on the configured port
> Troubleshooting steps:
> Check the system event log for error messages
> Enable logging the application process' stdout messages
> Attach a debugger to the application process and inspect
> For more information visit: https://go.microsoft.com/fwlink/?LinkID=808681
> 
> I am on .Net Core 2.2. I suspect this is a compatibility issue.

This package has dependency of Newtonsoft.Json. Try adding it and see whether it works.

**Comment by SeppPenner** [comment]
Wait. Why didn't I get the notifications for this repository if I own it? 😕 It is maintained but I didn't see the issues. Sorry for that. I will check this soon, of course.

**Comment by cssriraman** [comment]
It works fine after adding Newtonsoft.Json and Serilog.Sinks.PeriodicBatching nuget packages. please refer my sample project

https://github.com/cssriraman/SerilogTeamsSample

Make sure you configure your own webHookUri in appsettings.json file.

> After installing via NuGet, upon running the application (without setting any additional configuration), I received this error -
> 
> HTTP Error 502.5 - ANCM Out-Of-Process Startup Failure
> Common causes of this issue:
> The application process failed to start
> The application process started but then stopped
> The application process started but failed to listen on the configured port
> Troubleshooting steps:
> Check the system event log for error messages
> Enable logging the application process' stdout messages
> Attach a debugger to the application process and inspect
> For more information visit: https://go.microsoft.com/fwlink/?LinkID=808681
> 
> I am on .Net Core 2.2. I suspect this is a compatibility issue.

**Comment by JoeYong** [comment]
I do have Newtonsoft.Json installed and it is running the same version as in your repo. I notice that your project is Web API, whereas mine is Web app.

> It works fine after adding Newtonsoft.Json and Serilog.Sinks.PeriodicBatching nuget packages. please refer my sample project
> 
> https://github.com/cssriraman/SerilogTeamsSample
> 
> Make sure you configure your own webHookUri in appsettings.json file.
> 
> > After installing via NuGet, upon running the application (without setting any additional configuration), I received this error -
> > HTTP Error 502.5 - ANCM Out-Of-Process Startup Failure
> > Common causes of this issue:
> > The application process failed to start
> > The application process started but then stopped
> > The application process started but failed to listen on the configured port
> > Troubleshooting steps:
> > Check the system event log for error messages
> > Enable logging the application process' stdout messages
> > Attach a debugger to the application process and inspect
> > For more information visit: https://go.microsoft.com/fwlink/?LinkID=808681
> > I am on .Net Core 2.2. I suspect this is a compatibility issue.

**Comment by SeppPenner** [comment]
@cssriraman @JoeYong I still don't know why you would need to add `Newtonsoft.Json` and `Serilog.Sinks.PeriodicBatching`...

**Comment by cssriraman** [comment]
> @cssriraman @JoeYong I still don't know why you would need to add `Newtonsoft.Json` and `Serilog.Sinks.PeriodicBatching`...

Without adding these packages, I am getting error saying respective dlls not found.

**Comment by SeppPenner** [comment]
Okay... The funny thing is that they should be referenced properly already: https://github.com/SeppPenner/Serilog.Sinks.MicrosoftTeams/blob/5f4a7a56e7488fe8017618c8671c568cc7d098de/Serilog.Sinks.MicrosoftTeams/Serilog.Sinks.MicrosoftTeams/Serilog.Sinks.MicrosoftTeams.csproj#L55

I will check this soon (I sadly don't have a lot of time at the moment).

**Comment by SeppPenner** [comment]
There is a new version of the package available soon: https://www.nuget.org/packages/HaemmerElectronics.SeppPenner.Serilog.Sinks.MicrosoftTeams/1.0.3.

Please check if this still occurs...

**Comment by JoeYong** [comment]
> > @cssriraman @JoeYong I still don't know why you would need to add `Newtonsoft.Json` and `Serilog.Sinks.PeriodicBatching`...
> 
> Without adding these packages, I am getting error saying respective dlls not found.

I did a quick test and getting the same error, even with Newtonsoft JSON installed -
https://github.com/JoeYong/TestMSTeam1


> There is a new version of the package available soon: https://www.nuget.org/packages/HaemmerElectronics.SeppPenner.Serilog.Sinks.MicrosoftTeams/1.0.3.
> 
> Please check if this still occurs...

Thanks, but using the same test repo that I have, still getting the same error.

**Comment by SeppPenner** [comment]
Strange. I will have to check this again with your test repo...

**Comment by SeppPenner** [comment]
I maybe might have to add this: https://docs.microsoft.com/de-de/nuget/reference/nuspec#dependencies-element manually... I will check this and provide a new version if it works...

**Comment by SeppPenner** [comment]
Now I understand the real problem. Maybe it would already help to make the project available on NetCore. At the moment, I only have net45, net46, net462, net47, net472,net48 and netstandard2.0 (Which should be compatible with NetCore 2.2).

**Comment by SeppPenner** [comment]
I have now added the dependencies and provide an explicit build for NetCore 2.2 and NetCore 3.0 as well. The new nuget package should be available soon: https://www.nuget.org/packages/HaemmerElectronics.SeppPenner.Serilog.Sinks.MicrosoftTeams/1.0.3.1.

I will try this with the example project as well. If this wasn't the root caus, I honestly have no idea what else to check...

**Comment by SeppPenner** [comment]
I'm really looking forward to NetCore 5.0... Only one build for all platforms. Hurrayy 🚀

**Comment by JoeYong** [comment]
The good news is, it no longer crashes my app. The bad news is, it does not seem to work. It works similar to another repo - it outputs everything to the channel. But the moment I put in the minimum level, it does nothing, even if I put in Information or manually tries to log it using logger.LogInformation("Information Test").. Does this package support appsettings? As that is what I put in for our Serilog config -

                     "WriteTo": [
			{
				"Name": "Console",
				"theme": "Serilog.Sinks.SystemConsole.Themes.AnsiConsoleTheme::Code, Serilog.Sinks.Console"
			},			
			{
				"Name": "MicrosoftTeams",
				"Args": {
					"webHookUri": "URL",
					"title": "Error-Log",
					"restrictedToMinimumLevel": "Information"
				}
			},
			{
				"Name": "File",
				"Args": {
					"path": "C:\\Logs\\App-Log-%COMPUTERNAME%-.json",
					"formatter": "Serilog.Formatting.Json.JsonFormatter, Serilog",
					"rollingInterval": "Day",
					"retainedFileCountLimit": "",
					"rollOnFileSizeLimit": true,
					"restrictedToMinimumLevel": "Information",
					"shared": true
				}
			}
		],

**Comment by SeppPenner** [comment]
> The good news is, it no longer crashes my app. The bad news is, it does not seem to work. It works similar to another repo - it outputs everything to the channel. But the moment I put in the minimum level, it does nothing, even if I put in Information

Well, okay. At least something. I will open another issue for this because this issue is getting too big already.

> Does this package support appsettings? As that is what I put in for our Serilog config 

I guess not. `Serilog.Teams.Configuration` would be needed for this?

**Comment by SeppPenner** [comment]
So, this issue should be fixed with the latest version.
