### ISSUE TITLE
Formatting improvement

### ISSUE THREAD

**Issue by lucashutyler** [serilog-contrib/Serilog.Sinks.MicrosoftTeams.Alternative#11]
I'm logging an exception (stack trace) to Teams and it could use some newlines for readability. There are also some backticks in my stack trace that leads to Teams thinking it should render the section between as code (monospace font with a background). Sounds like there needs to be some html escaping or conversion?

**Comment by SeppPenner** [comment]
Do you have an example message maybe? I agree that HTML escaping would be useful, I will check this.

**Comment by lucashutyler** [comment]
![download_20210103_115951](https://user-images.githubusercontent.com/6248882/103487578-57ab4f80-4dbb-11eb-8510-4f5e08cd980e.png)
Here's an example where sections of a stack trace are formatted as code blocks.

**Comment by lucashutyler** [comment]
Not that the stack trace contains backticks that are not visible in the image above as those are what cause the beginning and end of the code blocks.

**Comment by SeppPenner** [comment]
I'll have to write some useful tests now 😄

**Comment by SeppPenner** [comment]
So, I don't really have an idea how I can escape all possible variations of markdown elements...

Would it be sufficient for you if I add a property called `useCodeTagsForMessage` which, if set to `true`, renders the whole message template as code (Would at least avoid the strange formatting you have right now)?

Example below:

![grafik](https://user-images.githubusercontent.com/9639361/103575629-4e60d680-4ed2-11eb-9b42-14962cf5488a.png)

**Comment by SeppPenner** [comment]
Version 1.2.0 of the package contains the option already. Maybe you can give it a try :)

**Comment by SeppPenner** [comment]
I will close this now, if you have some different ideas how to treat this, please give me a short update.
