### ISSUE TITLE
Add option for hiding properties section in message

### ISSUE THREAD

**Issue by mbardynin** [serilog-contrib/Serilog.Sinks.MicrosoftTeams.Alternative#2]
In the current implementation, it is not possible to control how message will look like. 
For example Properties section in most cases looks like noise in ms teams channel.
Would be great to have an option like omitPropertiesSection:
```c#
var logger = new LoggerConfiguration()
	.WriteTo.MicrosoftTeams(webHookUri, title: title, omitPropertiesSection: true)
    .CreateLogger();
```

**Comment by SeppPenner** [comment]
Wait. Why didn't I get the notifications for this repository if I own it? 😕 It is maintained but I didn't see the issues. Sorry for that. I will check this soon, of course.
