### ISSUE TITLE
Filtered output and multiple channels

### ISSUE THREAD

**Issue by nelsonroliveira** [serilog-contrib/Serilog.Sinks.MicrosoftTeams.Alternative#22]
# Support for filtering output events and multiple channels

A common usage case for me is logging only certain events to teams, i do this by adding a "logger" sink with a filter expression to search for a specific property.

Recently i had a request to log to multiple channels, this could be done by adding several more sinks with the different filters and url, but this would make the configuration file extremely verbose.

Would this project be willing to accept a PR to add:
1. Option to filter and send only events containing a specific property
2. Option to set a dictionary for the url to be used for the value found in the filter property (multiple channels support)

## Proposed workings
1. The user of the sink sets it to filter on events that have a property "MsTeams" (for example)
2. before logging an event the user adds the property "MsTeams" with whatever value represents the intended channel
3. During the push of the events
    * if the "MsTeams" property exists, it's value is searched as a key in the url dictionary to get the targeted url
    * if the value for the "MsTeams" is not found in the url dictionary, use the default url for the sink
    * if there is no property with that name, discard the event

## Proposed configuration json

```json
        "WriteTo": [
        {
            "Name": "MicrosoftTeams",
            "Args": {
                "webHookUri": "https://example.com/defaultChannel",
                "channelHandler": {
                    "filterOnProperty": "MsTeams",
                    "channelList": {
                        "MainChannel": "https://example.com/MainChannel",
                        "ITChannel": "https://example.com/ITChannel"
                    }
                }
            }
        }
    ]
````

## Final thoughts

This is still a rough idea of what would be needed, but i would like to contribute this to the community in a way that would be useful for everyone.

**Comment by SeppPenner** [comment]
If you ask me, it's a good idea. If you're willing to provide a pull request, I will look over it and check it :)

**Comment by nelsonroliveira** [comment]
Still a work in progress but would appreciate some guidance to see if it's going in the right direction

**Comment by nelsonroliveira** [comment]
PR ready for review

**Comment by SeppPenner** [comment]
I will take a look at it soon.

**Comment by SeppPenner** [comment]
@all-contributors please add @nelsonroliveira for code doc

**Comment by SeppPenner** [comment]
New version will be available soon.
