### ISSUE TITLE
Messages not going out.

### ISSUE THREAD

**Issue by clstr** [serilog-contrib/Serilog.Sinks.MicrosoftTeams.Alternative#25]
Trying to get serilog to sink to Microsoft Teams, but nothing i'm doing is working. any ideas? 

Writing to console still works fine. 
I know the webhook endpoint works as i tested it using curl.

https://gist.github.com/clstr/85367e0a2130ba20b105a646569a63e5

**Comment by nelsonroliveira** [comment]
Hum, I currently do not have access to a test teams room but I can see messages are being sent from the code you provided.

How was the teams room webhook setup?

![image](https://user-images.githubusercontent.com/10381502/177051206-8f7b3ef4-a48f-47b9-87d2-e8a1307e6f7e.png)

**Comment by clstr** [comment]
@nelsonroliveira There isn't much in the way of setting up a channel with a webhook, it is literally a 1 click process and it gives you the webhook address automatically.

https://docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/add-incoming-webhook

**Comment by nelsonroliveira** [comment]
Could you try with this plugin instead?

![image](https://user-images.githubusercontent.com/10381502/177341847-ffa7562f-e79e-4adb-96f4-89d23b0fef77.png)

**Comment by SeppPenner** [comment]
Sorry for the long delay. I have also no idea here. Whenever I tested it, it worked with the web hook...

**Comment by SeppPenner** [comment]
@clstr Some news here? Is this fixed already?

**Comment by clstr** [comment]
@SeppPenner Sorry, I fell ill and never had the chance to take a look again. Maybe, I should close and try it again later?

**Comment by SeppPenner** [comment]
> @SeppPenner Sorry, I fell ill and never had the chance to take a look again. Maybe, I should close and try it again later?

Oh, no problem. Get well soon :) And if the issue occurs again, just create another issue or re-open this issue.
