### ISSUE TITLE
The version 1.4.0 doesn't work with .NET 6.0. 

### ISSUE THREAD

**Issue by Kipotlov** [serilog-contrib/Serilog.Sinks.MicrosoftTeams.Alternative#30]
The version 1.3.0 works well.

The dll in the package directory ( serilog.sinks.microsoftteams.alternative\1.4.0\lib\net6.0 ) targets .NET 7.0.

Here is the exception:
System.IO.FileNotFoundException: 'Could not load file or assembly 'System.Runtime, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.'

**Comment by SeppPenner** [comment]
Can you try version 1.4.1? Should be out soon.

**Comment by Kipotlov** [comment]
The version 1.4.1 doesn't work either.

Now it's looking for .NET 8.0 :

System.IO.FileNotFoundException: 'Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.'

The dll in the package directory for .NET 6.0 targets .NET 8.0 :
[assembly: TargetFramework(".NETCoreApp,Version=v8.0", FrameworkDisplayName=".NET 8.0")]

**Comment by SeppPenner** [comment]
> The version 1.4.1 doesn't work either.
> 
> Now it's looking for .NET 8.0 :
> 
> System.IO.FileNotFoundException: 'Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.'
> 
> The dll in the package directory for .NET 6.0 targets .NET 8.0 : [assembly: TargetFramework(".NETCoreApp,Version=v8.0", FrameworkDisplayName=".NET 8.0")]

Baah... I don't understand the issue to be honest. Need to take a depper dive here to find where this really comes from...

**Comment by Kipotlov** [comment]
I downloaded your code and when I build it in VS everything is fine.

I think the problem is on the build and upload of the nuget package. Locally, the script to build it (BuildAndPushPackage.bat) generates only one dll. It looks like you upload the same dll for all 3 target frameworks.
I have never done that, so I cannot help you.

**Comment by SeppPenner** [comment]
The build is the problem, yes. I think, I can fix it.

**Comment by SeppPenner** [comment]
Can you try 1.4.2, please? This should now finally fix the issue :D

**Comment by Kipotlov** [comment]
Yeah, it's fixed. Thank you

**Comment by SeppPenner** [comment]
> Yeah, it's fixed. Thank you

Nice :)
