### ISSUE TITLE
Version 1.4.4.0 broken due to periodicbatching nuget update

### ISSUE THREAD

**Issue by hellcoderGIT** [serilog-contrib/Serilog.Sinks.MicrosoftTeams.Alternative#31]
Serilog.Sinks.Elasticsearch.ElasticsearchSink is sealed error.

Should be this problem:
https://github.com/serilog-contrib/serilog-sinks-elasticsearch/pull/579

I guess just wait for the next version of PeriodBatching.

**Comment by SeppPenner** [comment]
Oh shit, I didn't see this one. Yes, we should wait for the next version.

**Comment by SeppPenner** [comment]
Should be fixed in v1.4.5.
