### ISSUE TITLE
Bump version of Serilog.Sinks.PeriodicBatching to 4.1.1

### ISSUE THREAD

**Issue by mprice-gcmlp** [serilog-contrib/Serilog.Sinks.MicrosoftTeams.Alternative#32]
There's an issue with Serilog.Sinks.PeriodicBatching for .NET 6. I implemented a fix for it in 4.1.1. 

https://github.com/serilog/serilog-sinks-periodicbatching/issues/80

Was giving an error 

`Could not load file or assembly 'System.Threading.Channels, Version=8.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.`

**Comment by SeppPenner** [comment]
Fixed with https://github.com/serilog-contrib/Serilog.Sinks.MicrosoftTeams.Alternative/commit/97f9d71a73c2de13e872f6932ecd2d1dbeb2abfd.
