### ISSUE TITLE
Support for Teams Workflows in place of deprecated Incoming Webhook Connector

### ISSUE THREAD

**Issue by jordan-reato** [serilog-contrib/Serilog.Sinks.MicrosoftTeams.Alternative#35]
Microsoft have marked Incoming Webhook Connector for deprecation:
https://techcommunity.microsoft.com/t5/teams-developer/simple-workflow-to-replace-teams-incoming-webhooks/m-p/4225270

Are there plans for this package to support for posting to Teams using Workflows instead?

**Comment by SeppPenner** [comment]
Will be done in https://github.com/serilog-contrib/Serilog.Sinks.MicrosoftTeams.Alternative/issues/33.
