### ISSUE TITLE
Choice of license

### ISSUE THREAD

**Issue by torerikh** [serilog-contrib/Serilog.Sinks.MicrosoftTeams.Alternative#5]
Have you considered using a more permissive license?

**Comment by SeppPenner** [comment]
Which kind of "more permissive" do you mean? Or in which direction? Allowing closed sources?

![image](https://user-images.githubusercontent.com/9639361/67871517-c2feef00-fb30-11e9-9865-4f9d749152ad.png)
https://choosealicense.com/licenses/gpl-3.0/

**Comment by SeppPenner** [comment]
@torerikh And which license would you suggest?

**Comment by torerikh** [comment]
The background for the question is that using or including a component that uses gpl style licenses is difficult for commercial/closed source products/solutions. A licence like e.g. MIT which is the licenses of the original library you forked would make usage in those scenarios simpler/possible. But, choice of licenses is as always entirely up to the creators and there are good reasons for the gpl style of licenses aswell :)

**Comment by SeppPenner** [comment]
I have adjusted the license to the MIT license. I will update the nuget package soon. I see the point of your argumentation and therefore agree that it would be a good idea to switch to the MIT license.

**Comment by SeppPenner** [comment]
The package is updated as well. It will be available under https://www.nuget.org/packages/HaemmerElectronics.SeppPenner.Serilog.Sinks.MicrosoftTeams/1.0.3.2 soon :)
