### ISSUE TITLE
Enhancement:  Add an option pass in outputTemplate 

### ISSUE THREAD

**Issue by bdshah1** [serilog-contrib/Serilog.Sinks.MicrosoftTeams.Alternative#9]
This is a great sink.   I am wondering if it is possible to configure outputTemplate for message.  Similar to Console or Email Sink.

**Comment by SeppPenner** [comment]
This is a good idea. I will try to add this soon.

**Comment by SeppPenner** [comment]
Fixed with https://github.com/SeppPenner/Serilog.Sinks.MicrosoftTeams/commit/4958543be0df50c1488ac27869edd551af4f8b13. Will be in version 1.1.1. Can you please test this for me? :)
